### ISSUE TITLE
aws-sigv4 fails to normalize duplicate `/` in URLs

### ISSUE THREAD

**Issue by rcoh** [smithy-lang/smithy-rs#1308]
Reproducer: 
1. pick operation with a greedy path label
2. pass `//`

the quick-hack fix:
```rust
        let path = Cow::Owned(path.replace("//", "/"));
```

**Comment by rcoh** [comment]
From: https://docs.aws.amazon.com/general/latest/gr/sigv4-create-canonical-request.html
```
Add the canonical URI parameter, followed by a newline character. The canonical URI is the URI-encoded version of the absolute path component of the URI, which is everything in the URI from the HTTP host to the question mark character ("?") that begins the query string parameters (if any).

Normalize URI paths according to [RFC 3986](https://tools.ietf.org/html/rfc3986). Remove redundant and relative path components. Each path segment must be URI-encoded twice ([except for Amazon S3 which only gets URI-encoded once](https://docs.aws.amazon.com/AmazonS3/latest/API/sigv4-query-string-auth.html)).

Example Canonical URI with encoding

/documents%2520and%2520settings/
Note
In exception to this, you do not normalize URI paths for requests to Amazon S3. For example, if you have a bucket with an object named my-object//example//photo.user, use that path. Normalizing the path to my-object/example/photo.user will cause the request to fail. For more information, see [Task 1: Create a Canonical Request](https://docs.aws.amazon.com/AmazonS3/latest/API/sig-v4-header-based-auth.html#canonical-request) in the Amazon Simple Storage Service API Reference.

If the absolute path is empty, use a forward slash (/). In the example IAM request, nothing follows the host in the URI, so the absolute path is empty.

Example Canonical URI

/
```

**Comment by rcoh** [comment]
linked: https://github.com/awslabs/smithy-rs/issues/1308

**Comment by ysaito1001** [comment]
We should clarify that normalizing duplicated forward slashes is not part of URI path normalization for creating canonical requests as two or more slashes should be valid, in which case we have an empty path segment.

Regarding a failing reproduction steps in [aws-sdk-rust#661](https://github.com/awslabs/aws-sdk-rust/issues/661), it is caused by the fact that slashes are [not allowed](https://docs.aws.amazon.com/AmazonS3/latest/userguide//bucketnamingrules.html) in the name of an S3 bucket. One way to address it is to return an error by saying such a bucket name is not supported and not let an HTTP request make its way to the S3 service. A reference implementation can be found in [`isValidDnsBucketName`](https://github.com/aws/aws-sdk-java-v2/blob/584ccb59e770177aeaa4c3b6bda4e24015b8ece9/services/s3/src/main/java/software/amazon/awssdk/services/s3/internal/BucketUtils.java#L50) in Java SDK V2.

When implemented in Rust SDK, this would need to an S3 customization where we add a validation function in `inlineable` and then pull that in via the `make_operation` customization.

**Comment by jdisanti** [comment]
Looks like this was fixed a while ago.
