### ISSUE TITLE
Provide a way to access Lambda Context in Python

### ISSUE THREAD

**Issue by unexge** [smithy-lang/smithy-rs#1815]
[lambda_http](https://crates.io/crates/lambda_http) crate provides [RequestExt](https://docs.rs/lambda_http/latest/lambda_http/ext/trait.RequestExt.html) trait to allow accessing some additional information. Currently we convert Lambda request to Hyper request in: https://github.com/awslabs/smithy-rs/blob/main/rust-runtime/aws-smithy-http-server/src/routing/lambda_handler.rs#L49-L89 ~~and we lose the information that specific to Lambda. Ideally we should provide a way to access that information.~~

I'm not sure what is the best way to do that, maybe we can discuss about adding Lambda specific traits to Smithy IDL, or maybe we can provide that information ~~via `Request::extensions` in Rust and~~ with a `app.lambda_context` decorator in Python.

**Comment by david-perez** [comment]
Most of that information is stored in request extensions already by the Lambda runtime (e.g. [`RequestContext`](https://docs.rs/lambda_http/latest/src/lambda_http/ext.rs.html#256-261)), which we preserve in that `convert_event` function since we reconstruct the request with the converted body type using [`http::Request::from_parts(parts, body)`](https://github.com/awslabs/smithy-rs/blob/4c852b1d0b4456493869db13a934eecb5c81657b/rust-runtime/aws-smithy-http-server/src/routing/lambda_handler.rs#L88).

So to access it as of now, the user just has to model it in their `State` and `AddExtensionLayer` will take care of extracting it.

However, I do think that the general problem of threading _request-specific_ state to service handlers (as opposed to global application state), which includes things like Lambda context, peer IP address, request ID, etc. needs to be solved more ergonomically.

**Comment by unexge** [comment]
@david-perez ohh I missed that. I'll convert this issue to be Python specific. Do we have a tracking ticket for the last part or do you want me to create a ticket for that?
