### ISSUE TITLE
Implement event streaming initial messages in AwsJson

### ISSUE THREAD

**Issue by 82marbag** [smithy-lang/smithy-rs#2237]
https://github.com/awslabs/smithy-rs/pull/2230 throws an exception if a non-streaming member and a streaming-member are in the payload of an AwsJson 1.0 request/response.

https://github.com/awslabs/smithy/issues/1584 confirmed this constraint is not required and we should relax it. Note that this is backwards compatible.

**Comment by david-perez** [comment]
Relevant code:

https://github.com/awslabs/smithy-rs/blob/c901c0b1c69ddbae350529c0f8116c4ab06fd348/codegen-core/src/main/kotlin/software/amazon/smithy/rust/codegen/core/smithy/protocols/AwsJson.kt#L51-L59

In other words, this issue is saying we haven't implemented [initial messages](https://smithy.io/2.0/spec/streaming.html#initial-messages) in the awsJson1.x protocols.

**Comment by jdisanti** [comment]
Duplicate of #121
