### ISSUE TITLE
Why reimplementing a stream?

### ISSUE THREAD

**Issue by Samrose-Ahmed** [smithy-lang/smithy-rs#3361]
For the PaginationStream. 

A Stream is a basic thing in Rust, everyone uses it, theres tons of utilities and code around. It seems you have replaced it with a custom type that resembles a stream but is not actually a Stream. I see https://github.com/smithy-lang/smithy-rs/issues/2413 but can we at least provide an opt in compat or something, it makes it very difficult and weird to work with.

**Comment by Samrose-Ahmed** [comment]
It seems I can use something like this which is not too bad, but just weird:

```rust
pub struct SmithyStreamAdapt<I>(PaginationStream<I>);
impl <I> Stream for SmithyStreamAdapt<I> {
    type Item = I;

    fn poll_next(mut self: std::pin::Pin<&mut Self>, cx: &mut std::task::Context<'_>) -> std::task::Poll<Option<Self::Item>> {
        self.0.poll_next(cx)
    }
}
```

**Comment by jdisanti** [comment]
It's a consequence of not being able to make breaking changes to the SDK after the GA launch. Since the Rust Async Working Group is actively working on a stable replacement for the Stream trait, we consider it to be unstable and a risk for future breaking changes. I agree that it's not ideal though. Hopefully we get something in the standard library sooner than later.

In the meantime, we just released a convenience in the [aws-smithy-types-convert](https://crates.io/crates/aws-smithy-types-convert) crate behind the `convert-streams` feature that allows you to convert our paginators back into streams:
```rust
use aws_smithy_types_convert::stream::PaginationStreamExt;

let stream = s3_client.list_objects_v2().bucket("...").into_paginator().send().into_stream_03x();
```
Thank you, @Ploppz, for the contribution.

**Comment by Samrose-Ahmed** [comment]
Ok thanks for the reply.
