### ISSUE TITLE
Usage of (protocol_serde) serializers on auto generated smithy shapes outside of the autogenerated crate 

### ISSUE THREAD

**Issue by aslavkinamazon** [smithy-lang/smithy-rs#3505]
Hey team,
I want to use smithy model to share shapes (which aren’t connected directly to the service) between several components. In one of those components I need to serialize the object and send it through Kinesis then fetch it in another. Smithy (rs) generating serializers under protocol_serde which is pub(crate) mod, meaning that I can’t use it outside of the client crate.
I saw quite a lot of request in the slack channels from developers that want to be able to use smithy for same purpose as I do (not necessarily with Kinesis use case but the point is clear) and this issue is a series blocker.
Disclaimer: Client package doesn't hold the code, only the the compiling configuration and build it with the the one that uses it so manual removal of (crate) is not an option.
Thanks

**Comment by jdisanti** [comment]
I don't think this is something we want to support, and I also don't think it would cover the functionality you desire either. Some services have asymmetric protocol serializers/deserializers. That is to say, serialization may be in AwsQuery format while deserialization may be in RestXml format. Thus, you wouldn't be able to round trip the value in that case. Using the protocol serde also restricts your model from changing the protocols in the future, because now your application's implementation relies on the format.

What you want instead is more general `serde` crate `Serialize`/`Deserialize` implementations, which someone has been contributing with [RFC30](https://github.com/smithy-lang/smithy-rs/pulls?q=is%3Apr+rfc30+).
